name: low-env-pipeline

on:
  push:
    branches:
      - 'main'
      - 'pipeline'
    # paths:
    #   - 'infra/**'
  workflow_dispatch:

env:
  working-dir: './infra/terraform'
  TF_environment: "test"
  TF_region: ${{ secrets.TF_REGION }}
  TF_appname: "microservice-store-demo"

jobs:
  run-trivy-scanner:
    if: false
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Trivy vulnerability scanner in IaC mode for Terraform
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          scan-ref: ${{ env.WORKING_DIR }}
          hide-progress: true
          format: 'sarif'
          output: 'trivy-terraform-results.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-terraform-results.sarif'
          category: terraform-analysis-tool

  create-low-env-infra:
    runs-on: ubuntu-latest
 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.TF_BUCKET }}" \
          -backend-config="key=${{ secrets.TF_STATE_KEY }}" \
          -backend-config="region=${{ env.TF_REGION }}"
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -detailed-exitcode \
          -var "environment=${{ env.TF_ENVIRONMENT }}" \
          -var "region=${{ env.TF_REGION }}" \
          -var "appname=${{ env.TF_APPNAME }}"
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Apply
      if: steps.plan.outputs.exitcode == 2  # Só aplica se houver mudanças
      run: |
        terraform apply -auto-approve \
          -var "environment=${{ env.TF_ENVIRONMENT }}" \
          -var "region=${{ env.TF_REGION }}" \
          -var "appname=${{ env.TF_APPNAME }}"
      working-directory: ${{ env.WORKING_DIR }}
