name: low-env-pipeline

on:
  push:
    branches:
      - 'main'
      - 'pipeline'
  #   paths:
  #     - 'infra/**'
  workflow_dispatch:

env:
  WORKING_DIR: './infra/terraform'
  TF_ENVIRONMENT: "test"
  TF_REGION: ${{ secrets.TF_REGION }}
  TF_APPNAME: "microservice-store-demo"
  TF_ACCOUNT_ID: ${{ secrets.TF_ACCOUNT_ID }}
  TF_ROLE_NAME: ${{ secrets.TF_ROLE_NAME }}
  TF_DYNAMODB_TABLE: ${{ secrets.TF_DYNAMODB_TABLE }}
  TF_BUCKET: ${{ secrets.TF_BUCKET }}
  TF_STATE_KEY: "state/microservice-store-demo/low-env/terraform.tfstate"
permissions:
  id-token: write
  contents: read

jobs:
  security-scan:
    name: "Security Scan: Trivy IaC Analysis"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Trivy vulnerability scanner in IaC mode for Terraform
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          scan-ref: ${{ env.WORKING_DIR }}
          hide-progress: true
          format: 'sarif'
          output: 'trivy-terraform-results.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-terraform-results.sarif'
          category: terraform-analysis-tool

  plan-infra:
    name: "Provision Low Environment Infrastructure"
    runs-on: ubuntu-latest
    needs: security-scan
    outputs:
      tf_exitcode: ${{ steps.plan.outputs.exitcode }}
    steps:
    - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.TF_ACCOUNT_ID }}:role/${{ env.TF_ROLE_NAME }}
        aws-region: ${{ env.TF_REGION }}

    - uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ env.TF_BUCKET }}" \
          -backend-config="key=${{ env.TF_STATE_KEY }}" \
          -backend-config="region=${{ env.TF_REGION }}" \
          -backend-config="encrypt=true" \
          -backend-config="dynamodb_table=${{ env.TF_DYNAMODB_TABLE }}"
      working-directory: ${{ env.WORKING_DIR }}

    - name: Generate Terraform Plan
      id: plan
      run: |
        terraform plan -detailed-exitcode \
          -var "environment=${{ env.TF_ENVIRONMENT }}" \
          -var "region=${{ env.TF_REGION }}" \
          -var "appname=${{ env.TF_APPNAME }}" \
          -out=tfplan
      working-directory: ${{ env.WORKING_DIR }}

    - name: Upload Terraform Plan
      if: steps.plan.outputs.exitcode == '2'
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ${{ env.WORKING_DIR }}/tfplan
        retention-days: 1

  apply-infra:
    environment: test
    name: "Apply Terraform Changes"
    runs-on: ubuntu-latest
    needs: plan-infra
    if: needs.plan-infra.outputs.tf_exitcode == '2'  # applies only if there are any changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.TF_ACCOUNT_ID }}:role/${{ env.TF_ROLE_NAME }}
          aws-region: ${{ env.TF_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.TF_REGION }}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ env.TF_DYNAMODB_TABLE }}" 
        working-directory: ${{ env.WORKING_DIR }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.WORKING_DIR }}

      - name: Apply Terraform Changes
        run: |
          terraform apply tfplan
        working-directory: ${{ env.WORKING_DIR }}