name: deploy-store-front

on:
  push:
    branches:
      - 'main'
      - 'pipeline'
    # paths:
    #   - 'src/store-front/**'

  workflow_dispatch:

permissions:
  contents: read
  packages: write
    
jobs:
  install-app-dependencies-and-test:
    runs-on: ubuntu-latest
    container:
      image: node:18.20.4-alpine
      # options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install app dependencies
        run: pwd && ls -lah&& npm install
        working-directory: 'src/store-front'
      - name: Unit tests
        run: npm test
        working-directory: 'src/store-front'
      - name: Build the app
        run: npm run build && pwd && ls -lah
        working-directory: 'src/store-front'
      - name: Upload artfacts
        uses: actions/upload-artifact@v4
        with:
          name: artfacts
          path: 'src/store-front/dist'
  unit-tests:
    needs: install-app-dependencies-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download artfacts
        uses: actions/download-artifact@v4
        with:
          name: artfacts
          path: 'app/dist'
      - name: package app
        run: tar -czf store-front-service.tar.gz ./app/dist
      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
          files: |
            store-front-service.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # deploy:


