name: deploy-store-front

on:
  push:
    branches:
      - 'main'
      - 'pipeline'
    # paths:
    #   - 'src/store-front/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
    
jobs:
  setup-and-test:
    name: "Install Dependencies & Run Tests"
    runs-on: ubuntu-latest
    container:
      image: node:18.20.4-alpine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: src/store-front/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('src/store-front/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

      - name: Install Dependencies
        run: npm install
        working-directory: 'src/store-front'

      - name: Run Unit Tests
        run: npm test
        working-directory: 'src/store-front'

  build-app:
    name: "Build Store Front Application"
    needs: setup-and-test
    runs-on: ubuntu-latest
    container:
      image: node:18.20.4-alpine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: src/store-front/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('src/store-front/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

      - name: Build Application
        run: npm run build
        working-directory: 'src/store-front'

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: store-front-artifacts
          path: 'src/store-front/dist'

  package-and-release:
    name: "Package & Create Release"
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: store-front-artifacts
          path: 'app/dist'

      - name: Package Application
        run: tar -czf store-front-service.tar.gz -C app/dist .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
          files: store-front-service.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  # deploy:


